---

#
# This file is part of the `src-run/cocoa-stemmer-library` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this source code.
#

sudo     : false
language : php
php      : [ 7.0, 7.1, nightly ]

git:
  depth : 3

env:
  global:
    - secure: "ZCLQbQRucUfOgv3b0JpoDLdOz+1kB+7YgsAZ0o9IEYHID/pa/xrkM6mb9hrgNgLnyfE28uSMXd/7FnDO/mq7EgRUYu3zPTh+nHYl+vDyygUBlSeOhBAkArlgLK20NKo/dt2e0nSKI64XXq0TNhWM1jeK9y7YvH5GcLN00rUTzjWytaGCBtqjuLeb6r+fubDTSlu8khfraaATwttnlyuZ1U71PxQF4kmBT09Gh48BEQFlka/vaq6Ytwt3NdCt+HOyR/JKUtUqcwasbNSDt4FsulanI2sLuKHFRdg2zig9Qglx9+QDdhM7f+t45HwARByVJ9QQjGy0qSTyahj5uWQpMJ2Sqr3YQ6ThcECK9qvfOW3O/8lO4IGlqgB85ZFGP4q3ewzU+pOqU8knI5MaAHDLoMFh8eLRB7Tvws6Fexp883VIuY9Q2KJs3AGRkoXz7aIngtVLHRm6M52zVUmaoJHU/tCfxdBWfjANTQNWmYDRLiXaOsXETlHek5wgxtvUIXNsHcqTz92z6iljrkzZ42k/qawUCb0x8rePmUXaND1NWD+ShEVLwDsSKr5WVl2xJ97rVYR247j6abNWRvRO44JnTdjIRWSfBvWt9Tt0aAdtiYvWLW+yJLY/C9umkpd60mTyJ+UbHxhTuygwuD0PSvK0G4qwWZ88OIZFFSDckmMWDVI="

install :
  - bash .bldr/bldr -b up-env -q
  - bash .bldr/bldr -b up-app -q

script :
  - bin/simple-phpunit || bin/phpunit

after_script :
  - bash .bldr/bldr -b down-app -q
  - bash .bldr/bldr -b down-env -q

...
